name: "Gestionar PRs inactivos"
on:
  schedule:
    - cron: "*/5 * * 1 1"  # Ejecuta el workflow cada 5 minutos
jobs:
  manage-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar acción stale
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GH_STALE_TOKEN }}
          days-before-pr-stale: 0.0035   # 5 minutos expresados en días
          days-before-pr-close: 0.0069  # 10 minutos expresados en días
          stale-pr-message: "Este PR ha estado inactivo durante 5 minutos y se ha marcado como inactivo. Se cerrará automáticamente en 5 minutos si no hay actividad adicional."
          close-pr-message: "Este PR se ha cerrado automáticamente después de 10 minutos de inactividad."
          stale-pr-label: "SIN_ACTIVIDAD"
